name = "BMesh"
uuid = "91fb467a-ecbd-11ec-0e64-1b9c3501232a"
authors = ["Eduardo Lenz <eduardobarplenz@gmail.com>"]
version = "0.1.0"


[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
